### ISSUE TITLE
Add navbar, body, and footer component for website 

### ISSUE THREAD

**Issue by sagelga** [sagelga/react-weather-app#1]
Create the website by design https://www.figma.com/file/i3Z4PcbicGiOy5Ux3QhFTX/Weather-React-App-v1?node-id=0%3A1&t=HgcHYWLKhPbFeUOW-1

## To-dos
- [x] Add navigation bar
- [x] Add body
    - [x] City
    - [x]  Current temperature
    - [x]  Current Feels like
    - [x]  Current weather
    - [x]  Current weather description 
- [x] Add cards for additional weather information (for #6)
- [x] Add footer
     - [x]  Add Source
     - [x]  Add link to GitHub profile
