### ISSUE TITLE
Makes a functional navbar

### ISSUE THREAD

**Issue by sagelga** [sagelga/react-weather-app#13]
## To-do

- [x] Add navigation bar component
- [x] Add SearchBar component into a navigation bar
- [x] Add Menu Toggle component to a navigation bar 
- [x] #45
- [x] #46
- [x] #47
