### ISSUE TITLE
Uses Open Weather API to retrieve weather data

### ISSUE THREAD

**Issue by sagelga** [sagelga/react-weather-app#6]
Retrieve data from Open Weather API (Docs : https://openweathermap.org/api/one-call-3)

## To-do
- [ ] Choose which data point to retrieve 
    - Temperature 
    - Feels Like
    - Humidity 
    - Main weather (i.e., Cloud) https://openweathermap.org/weather-conditions
    - Secondary weather (I.e., Scattered Clouds)
- [ ] Calls the API with parameters 
    - Metric api.openweathermap.org/data/3.0/onecall?lat=30.489772&lon=-99.771335&units=metric
    - Langauge
- [ ] Shows the data in HTML
- [ ] Put the data in the grid
