### ISSUE TITLE
Uses Unsplash as a weather main background

### ISSUE THREAD

**Issue by sagelga** [sagelga/react-weather-app#7]
## To-do

- [x] Sign up and retrieve Unsplash API
- [x] Create a function for retrieving Unsplash image URL
- [x] Throw the URL to <img> tag and visualize the image
- [x] When user change the searchQuery, the image changes 
- [ ] #52
- [ ] #53
- [ ] #54
