### ISSUE TITLE
Implement autocomplete for search bar

### ISSUE THREAD

**Issue by sagelga** [sagelga/react-weather-app#71]
## Todos 
- [ ] Populate valid city names
- [ ] Add feature of when user press enter when autocomplete suggest something, it auto fills and trigger search 
- [ ] Implement #27 with autocomplete
